[FILTER]
    Name   lua
    Match  *
    script /fluent-bit/etc/remove_ansi.lua
    call   remove_ansi

[FILTER]
    Name    grep
    Match   *
    Exclude log ${HEALTH_CHECK_PATH}

[OUTPUT]
    Name              cloudwatch_logs
    Match             *
    region            ${AWS_REGION}
    log_group_name    ${CW_LOG_GROUP}
    log_stream_prefix ecs/
    auto_create_group false
    log_key           log

[OUTPUT]
    Name              s3
    Match             *
    region            ${AWS_REGION}
    bucket            ${ECS_LOG_BUCKET}
    s3_key_format     /ecs-logs/%Y/%m/%d/%H%M%S.gz
    compression       gzip
    total_file_size   50M
    upload_timeout    10m
