  name: Build and Deploy to Azure App Service (Docker)

  on:
    workflow_dispatch:
  
  permissions:
    id-token: write
    contents: read
  
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
  
      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Set Environment Variables
        run: |
          KEY_VAULT_NAME=$(az keyvault list --query "[?ends_with(name, '${{ env.BRANCH_NAME }}')].name" -o tsv)
          echo "KEY_VAULT_NAME=${KEY_VAULT_NAME}"
          echo "ACR-NAME=$(az keyvault secret show --name "ACR-NAME" --vault-name ${KEY_VAULT_NAME} --query "value" -o tsv)"  >> $GITHUB_ENV
          echo "IMAGE-NAME=$(az keyvault secret show --name "IMAGE-NAME" --vault-name ${KEY_VAULT_NAME} --query "value" -o tsv)"   >> $GITHUB_ENV
          echo "BACKEND-WORKING-DIRECTORY=$(az keyvault secret show --name "BACKEND-WORKING-DIRECTORY" --vault-name ${KEY_VAULT_NAME} --query "value" -o tsv)"   >> $GITHUB_ENV
          echo "BACKEND-APP-SERVICE-NAME=$(az keyvault secret show --name "BACKEND-APP-SERVICE-NAME" --vault-name ${KEY_VAULT_NAME} --query "value" -o tsv)"   >> $GITHUB_ENV
          echo "RESOURCE-GROUP-NAME=$(az keyvault secret show --name "RESOURCE-GROUP-NAME" --vault-name ${KEY_VAULT_NAME} --query "value" -o tsv)"   >> $GITHUB_ENV
  
  
      - name: Docker login to ACR
        run: |
          az acr login --name ${{ env.ACR-NAME }}
  
      - name: Build and push Docker image to ACR
        run: |
          cd .${{ env.BACKEND-WORKING-DIRECTORY }}
          docker build \
            -t ${{ env.ACR-NAME }}.azurecr.io/${{ env.IMAGE-NAME }}:${{ github.sha }} \
            -t ${{ env.ACR-NAME }}.azurecr.io/${{ env.IMAGE-NAME }}:latest \
            .
  
          docker push ${{ env.ACR-NAME }}.azurecr.io/${{ env.IMAGE-NAME }}:${{ github.sha }}
          docker push ${{ env.ACR-NAME }}.azurecr.io/${{ env.IMAGE-NAME }}:latest
  
      - name: Deploy to App Service
        run: |
          az webapp config container set \
            --name ${{ env.BACKEND-APP-SERVICE-NAME }} \
            --resource-group ${{ env.RESOURCE-GROUP-NAME }} \
            --container-image-name ${{ env.ACR-NAME }}.azurecr.io/${{ env.IMAGE-NAME }}:${{ github.sha }} \
            --container-registry-url https://${{ env.ACR-NAME }}.azurecr.io
            
      - name: Restart App Service (optional)
        run: |
          az webapp restart \
            --name ${{ env.BACKEND-APP-SERVICE-NAME }} \
            --resource-group ${{ env.RESOURCE-GROUP-NAME }}
